### ISSUE TITLE
https://dndle.app/ stuck with "Loading... please wait..."

### ISSUE THREAD

**Issue by pyyhttu** [Dan-Q/dndle#1]
Noticed today https://dndle.app/ throws now:

```
Loading... please wait...

(If this doesn't go away, perhaps check is Javascript is enabled in your browser?)
```

This happens with every browser I have, in incognito modes as well.

Yesterday (27.3.2022) was still working fine.

**Comment by Dan-Q** [comment]
Working for me. Any useful errors in your browser's debug console? (Press `F12`, reload page, look in "Console" tab.)

**Comment by pyyhttu** [comment]
Strange. Now working, and can't reproduce this anymore on any of the same browsers (iOS Safari, Win64 Chrome & Firefox) I had this with.

If this reoccurs, I'll get the debug from console next time.

**Comment by pyyhttu** [comment]
Seems to happen again, about the same time as yesterday. New monster should've appeared about ~1 h ago.

Here's the console output from Chrome (latest version, stock settings):'

```
dndle.js:4 Uncaught ReferenceError: Cannot access 'W' before initialization
    at x (dndle.js:4:216)
    at dndle.js:50:7
    at dndle.js:171:1041
x @ dndle.js:4
(anonymous) @ dndle.js:50
(anonymous) @ dndle.js:171
```

Update: 13:11 EET: seems to be up again, and console does not show any errors anymore. I'll leave this open, as I suspect you're able to see this happening tomorrow after 12:00 EET. I tend to notice this then as usually have my lunch at that time.

**Comment by Dan-Q** [comment]
Interesting. The `W` in the compiled code is the instance of `Reef`. Sounds like a possible race condition. Taking a quick look.

**Comment by Dan-Q** [comment]
I'm still unable to replicate this locally, so I can't be sure I've got a fix. Would you mind experimentally going to https://dndle.app/next.html and see if that works for you?

**Comment by pyyhttu** [comment]
Yes, works fine. No errors produced in the console.

I believe the best bet to snatch this is tomorrow at around 12 EET when a new monster is updated, as this has happened now twice in a row.

I asked from a friend who plays this too, and he experienced the same "Loading... please wait..." error as I did yesterday, and today. The problem also went away for him at the same as it did for me.

**Comment by pyyhttu** [comment]
It's on again, 12:15 EET. 

https://dndle.app/ console output:

```
Uncaught ReferenceError: Cannot access 'W' before initialization
    at x (dndle.js:4:216)
    at dndle.js:50:7
    at dndle.js:171:1041
```

https://dndle.app/next.html console output:

```
dndle-next.js:547 Uncaught ReferenceError: Cannot access 'app' before initialization
    at updateCountdownTimer (dndle-next.js:547:7)
    at HTMLDocument.<anonymous> (dndle-next.js:557:3)
```

**Comment by Dan-Q** [comment]
Thanks. Managed to replicate it locally now!

**Comment by Dan-Q** [comment]
Very definitely a Daylight Savings problem. The _day_ we're on (for the purpose of choosing a monster) is calculated entirely in UTC, which is correct, but the "time until next monster" is calculated based on the date in your local timezone and _compared_ to the UTC date, which results in a discrepancy when daylight savings is in effect. The problem occurs during the "extra" hour each day.

**Comment by Dan-Q** [comment]
Experimental solution in place at https://dndle.app/next.html

**Comment by Dan-Q** [comment]
Should all be fixed now. You might have to "hard refresh" (e.g. `CTRL` + `F5` / `CMD` + `R`) on http://dndle.app/ to clear the broken JS from your cache, if you still see the problem.

Thanks for reporting this!

**Comment by Dan-Q** [comment]
(There's a _chance_ that anybody who experienced the bug _today_ before it was fixed might not be able to do today's monster: it'll be as if they already attempted it and failed - sorry!)
