### ISSUE TITLE
domain broke

### ISSUE THREAD

**Issue by BasLangenberg** [Dan-Q/dndle#7]
Hi!

Seems like this commit on the gh-pages branch broke the dndle.app domain.

https://github.com/Dan-Q/dndle/commit/a2f0769dabf4c6b9c91d0544b7ce5ac1bf207174

Our discord is in shambles now. Could you please add the CNAME record again? 😄

**Comment by Dan-Q** [comment]
Thanks for raising, and sorry! Fixed now!

**Comment by BasLangenberg** [comment]
Our discord is very happy again. :-)

Also, thanks for this amazing thing to spend my coffee breaks on!

**Comment by Dan-Q** [comment]
Honestly, I'm amazed people are using and enjoying this! I mostly made it as a joke!

Now I know, I'll be sure to renew the domain name when it comes up in February!
